home:
  alias: '/jsesh'

languages:
  supported:
    - fr
    - en    
    - es
    - it
  default_lang: en
  content_fallback:
    en: [] 
    fr: ['en']
    ja: ['en']
    es: ['en']
    it: ['en']
pages:
  theme: doc-theme
  markdown:
    extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
  purge_at: '0 4 * * 1'
  clear_at: '0 3 * * 1'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
